CREATE TABLE IF NOT EXISTS GITHUB_PROJECT(
    id UUID NOT NULL,
    org_name VARCHAR(50) NOT NULL,
    repo_name VARCHAR(50) NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS GENRE(
    id UUID NOT NULL,
    name VARCHAR(50) NOT NULL UNIQUE,
    category VARCHAR(25),
    description VARCHAR(250),
    created_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS READING_ENTRY(
     id UUID NOT NULL,
     title VARCHAR(100) NOT NULL UNIQUE,
     genre_id UUID NOT NULL,
     type VARCHAR(20),
     medium VARCHAR(20),
     favourite BOOLEAN,
     language VARCHAR(50),
     publisher VARCHAR(100),
     edition VARCHAR(15),
     created_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     PRIMARY KEY(id)
);

ALTER TABLE READING_ENTRY
    ADD CONSTRAINT fk_genre FOREIGN KEY (genre_id) REFERENCES GENRE;

CREATE TABLE  IF NOT EXISTS READING_RECORD(
    id UUID NOT NULL,
    reading_entry_id UUID NOT NULL,
    status VARCHAR(25),
    percentage_complete DECIMAL,
    start_date DATE,
    end_date DATE,
    completion_time DECIMAL,
    notes VARCHAR(500),
    created_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);

ALTER TABLE IF EXISTS READING_RECORD
    ADD CONSTRAINT fk_reading_entry FOREIGN KEY (reading_entry_id) REFERENCES READING_ENTRY;

CREATE TABLE AUTHOR(
    id UUID NOT NULL,
    name VARCHAR(100) NOT NULL UNIQUE,
    bio VARCHAR(250),
    website VARCHAR(100),
    notes VARCHAR(250),
    created_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS AUTHORSHIP(
    id UUID NOT NULL,
    reading_entry_id UUID NOT NULL,
    author_id UUID NOT NULL,
    created_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);


ALTER TABLE AUTHORSHIP
    ADD CONSTRAINT fk_reading_entry FOREIGN KEY (reading_entry_id) REFERENCES READING_ENTRY;

ALTER TABLE AUTHORSHIP
    ADD CONSTRAINT fk_author FOREIGN KEY (author_id) REFERENCES AUTHOR;

CREATE INDEX idx_title
    on READING_ENTRY (title);

CREATE INDEX idx_author
    on AUTHOR(name);

CREATE INDEX idx_repo_name
    ON GITHUB_PROJECT (repo_name);
